name: ssaccounts
description: Help you to visit google.
# version: 0.0.1
# homepage: https://github.com/lovetingyuan/free-ss

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  html: ^0.14.0+3
  http: ^0.12.1
  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  process_run: ^0.10.10+2
